### ISSUE TITLE
upgrade to latest wagmi

### ISSUE THREAD

**Issue by krisgrm** [memoriaXII/web3-typescript-fullstack#25]
This starter is using wagmin 0.6 there is 0.12 our already, any plans on upgrading?

**Comment by memoriaXII** [comment]
hey @krisgrm, thanks for much for your feedback, I am aware that wagmi 0.12 is now available, and I planning to upgrade to it in the coming days

**Comment by memoriaXII** [comment]
Hey@krisgrm, the package has been updated! https://github.com/memoriaXII/turborepo-web3-starter-kit/pull/26
